name: notes_app
description: A Flutter Notes Application
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  appwrite: ^12.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Correct: flutter_launcher_icons is a dev tool
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/
